<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>GApp Collection</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php echo $this->headLink(); ?>
    <?php echo $this->headScript(); ?>
</head>
<body>
    <div id="loading_container">
        Loading...
    </div>
    <div id="loaded_container" style="display: none;">
        <div class="header">
            <?php echo $this->navigation(); ?>
            <div class="signbox"><strong>Signed In</strong> | <a href="#">Sign Out</a></div>
        </div>
        <div class="content"><?php echo $this->layout()->content; ?></div>
    </div>
    <img src="<?php echo $this->baseUrl() ?>/img/dummy.gif" style="display:none" alt="required for Google Data"/>
</body>
</html>