<?php $report = $this->report; ?>
<a href="<?php echo $this->baseUrl() ?>/ganalytics/ajaxgetreports/table_id/<?php echo $report->getTableId(); ?>/" id="ga-report-back_link">« Back to reports</a>

<?php if (!count($report->getReferrers())) : ?>

<br /><br />Empty Result

<?php else : ?>

<table class="ga-report-info">
    <col width="150" />
    <col />
    <tbody>
        <tr>
            <td>Account:</td>
            <td><?php echo $report->getAccountName(); ?></td>
        </tr>
        <tr>
            <td>Profile:</td>
            <td><?php echo $report->getProfileName(); ?></td>
        </tr>
        <tr>
            <td>Table ID:</td>
            <td><?php echo $report->getTableId(); ?></td>
        </tr>
        <tr>
            <td>Minimum Traffic:</td>
            <td><?php echo $report->getMinTraffic(); ?></td>
        </tr>
        <tr>
            <td>Download Period:</td>
            <td><?php echo $report->getDownloadPeriod(); ?> day(s)</td>
        </tr>
        <tr>
            <td>Compare Period:</td>
            <td><?php echo $report->getComparePeriod(); ?> day(s)</td>
        </tr>
    </tbody>
</table>

<div class="ga-report-wrapper" id="ga-report-wrapper">
    <div class="ga-report-headline">
        <h3>#<?php echo $report->getId().' '.$report->getAccountName().' / '.$report->getProfileName(); ?></h3>
        <ul class="ga-report-headline-tools">
            <li><strong><?php echo count($report->getReferrers()) ?> new referrrer(s)</strong></li>
            <li><a href="<?php echo $this->baseUrl() ?>/ganalytics/csvreferrers/report_id/<?php echo $report->getId(); ?>/NewReferrersReport<?php echo $report->getId(); ?>.csv" class="csv-icon">Download as CSV</a></li>
        </ul>
    </div>
    <table cellspacing="0" cellpadding="0" class="ga-report" id="ga-report">
        <col width="200" />
        <col width="100" />
        <col  />
        <thead>
            <tr>
                <th><div>Host</div></th>
                <th><div>Visits</div></th>
                <th><div>Source URL</div></th>
            </tr>
        </thead>
        <tbody>
            <?php $referrers = $report->getReferrers(); ?>
            <?php foreach ($referrers AS $referrer) : ?>
            <tr>
                <td><?php echo $referrer['host'] ?></td>
                <td class="ga-report-center"><?php echo $referrer['total_visits'] ?></td>
                <td>
                    <ul class="ga-report-list">
                        <li class="ga-report-list-first">
                        <?php foreach ($referrer['pages'] AS $page) : ?>
                            <a href="<?php echo $page; ?>"><?php echo $page; ?></a></li><li>
                        <?php endforeach; ?>
                        </li>
                    </ul>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <div class="ga-report-headline">
        <h3>#<?php echo $report->getId().' '.$report->getAccountName().' / '.$report->getProfileName(); ?></h3>
        <ul class="ga-report-headline-tools">
            <li><strong><?php echo count($report->getReferrers()) ?> new referrrer(s)</strong></li>
            <li><a href="<?php echo $this->baseUrl() ?>/ganalytics/csvreferrers/report_id/<?php echo $report->getId(); ?>/NewReferrersReport<?php echo $report->getId(); ?>.csv" class="csv-icon">Download as CSV</a></li>
        </ul>
    </div>
</div>

<?php endif; ?>