<!-- base layout -->
<table cellspacing="0" cellpadding="0" class="ga-main-table">
    <col width="270" />
    <col />
    <thead><tr>
        <th><h2>New Report</h2></th>
        <th class="ga-main-right-col"><h2 id="ga_nr_contentheadline">Recent Reports</h2></th>
    </tr></thead>
    <tbody>
        <tr>
            <td>
                <?php echo $this->settingsForm; ?>
            </td>
            <td class="ga-main-right-col" id="ga-main-content">
                Loading...
            </td>
        </tr>
    </tbody>
</table>
<!-- /base layout -->